// <auto-generated />
using System;
using BeachEquipmentStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeachEquipmentStore.Data.Migrations
{
    [DbContext(typeof(EquipmentStoreDbContext))]
    [Migration("20250302170739_AddedCrationAndUpdateDatesToEntitiesAndPrimaryAddressColumn")]
    partial class AddedCrationAndUpdateDatesToEntitiesAndPrimaryAddressColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimaryAddress")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de3bb989-6d49-4f11-8113-ca0d70bfccea"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("e1e31b12-9ad2-43c2-adf1-24d1ebf5eb51"),
                            IsPrimaryAddress = false,
                            Name = "ул. Кракра №3",
                            Town = "София",
                            ZipCode = 1000
                        },
                        new
                        {
                            Id = new Guid("a0eb0f58-00f3-4f00-91ba-bc6ed1aa18db"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("854fc105-371f-40cb-a425-1e7bc09f0be8"),
                            IsPrimaryAddress = false,
                            Name = "кв. Овча Купел, ул. Рачка №9",
                            Town = "София",
                            ZipCode = 1000
                        },
                        new
                        {
                            Id = new Guid("2ba8d222-9501-490e-b4d3-fbd0e53131f0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("854fc105-371f-40cb-a425-1e7bc09f0be8"),
                            IsPrimaryAddress = false,
                            Name = "ул. Обзорски Тигър № 33",
                            Town = "Обзор",
                            ZipCode = 1000
                        });
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1e31b12-9ad2-43c2-adf1-24d1ebf5eb51"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44afbfa8-f120-4e24-a420-76c25a7f672c",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "p.petrov@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Petar",
                            LastName = "Petrov",
                            LockoutEnabled = false,
                            NormalizedEmail = "P.PETROV@MAIL.COM",
                            NormalizedUserName = "P.PETROV@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOdrJFPIFwjCUxAj1QV+y2yGOcc8tKSiPSeyy9PnyB17xlTug6UHPSffR6jtgNz6ww==",
                            PhoneNumber = "0876596224",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "df33cc02-7b8f-4500-807a-9fc4237610c0",
                            TwoFactorEnabled = false,
                            UserName = "p.petrov@mail.com"
                        },
                        new
                        {
                            Id = new Guid("854fc105-371f-40cb-a425-1e7bc09f0be8"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0da4c43a-1526-4d5e-b799-e11445ea075a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "n.flacko@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Nicko",
                            LastName = "Flacko",
                            LockoutEnabled = false,
                            NormalizedEmail = "N.FLACKO@MAIL.COM",
                            NormalizedUserName = "N.FLACKO@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEG23hUPlU0KheyLQsxVagoBV0RUSZNU8aXdVEcfC74K8WILq2sFjrrtOSq4K9D1Xjg==",
                            PhoneNumber = "0888202449",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d4d59c00-d681-44e3-9a7e-c1734f07bcd6",
                            TwoFactorEnabled = false,
                            UserName = "n.flacko@mail.com"
                        },
                        new
                        {
                            Id = new Guid("c721b444-85f6-4ed0-ab38-4ee57164d4bf"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "07e1a1e6-7c29-4bc5-8e72-918a23ba7c73",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "s.sarafov@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Stamat",
                            LastName = "Sarafov",
                            LockoutEnabled = false,
                            NormalizedEmail = "S.SARAFOV@MAIL.COM",
                            NormalizedUserName = "S.SARAFOV@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOc28g0b33ZYvtZ63pHKSidUK3eBldyCLydcpC4SMJFBoXeyy4IhfmMG+BkE0NxgmA==",
                            PhoneNumber = "0885527733",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45fff9bc-612f-44cc-9134-02aa661e4ed9",
                            TwoFactorEnabled = false,
                            UserName = "s.sarafov@mail.com"
                        });
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.CartItem", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/vv0FD1X/Bag-Category.webp",
                            Name = "Чанти"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/rHY9wjG/Ball-Category.jpg",
                            Name = "Топки"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/6nHY7VJ/Beach-Toy-Category.webp",
                            Name = "Плажни играчи"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/JxJ4CSM/Floaty-Category.webp",
                            Name = "Надувни"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/JkDDZkb/Swimming-Equipment-Category.jpg",
                            Name = "Обурудвабе за плуване"
                        },
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/w6CNrfd/Towel-Category.webp",
                            Name = "Плажни кърпи"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/t4KWPCP/Umbrella-Category.jpg",
                            Name = "Чадъри"
                        });
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/7WJYhkr/Vinex-Manufacturer.jpg",
                            Name = "Vinex"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/JpRqHbV/Covari-Manufacturer.jpg",
                            Name = "Coveri Collection"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/nQHgsJG/Cps-Manufacturer.jpg",
                            Name = "CPS TOYS"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/1nkCLZw/Dreamfox.jpg",
                            Name = "DREAMFOX"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/s2Y1245/Intex-Manufacturer.jpg",
                            Name = "INTEX"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/6PPhfyV/Publidea.jpg",
                            Name = "ПУБЛИИДЕЯ"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/QQ486yn/Shenzhen-Manufacturer.jpg",
                            Name = "Shenzhen Befine Sports Goods"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/K7N6Z0D/Shui-Manufacturer.jpg",
                            Name = "Shui Zhong Bao"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/CKCRztx/Star-Manufacturer.jpg",
                            Name = "Star"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ibb.co/bPDRFNJ/Vanguard-Manufacturer.jpg",
                            Name = "Vanguard Watersports"
                        });
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Barcode")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db8990fc-bbf1-45e0-9732-a64bfe743024"),
                            Barcode = 57532,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Памучна детска плажна хавлия с изообразени акула и рибки. Грамаж: 380 гр.",
                            ImageUrl = "https://i.ibb.co/LkpTB85/Towel-Shark.jpg",
                            ManufacturerId = 4,
                            Name = "Плажна хавлия DREAMFOX 75 x 170 cm.",
                            Price = 12.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("c7350597-79cd-45ac-9ff1-e9635b57966a"),
                            Barcode = 38527,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Микрофибърна плажна хавлия с изоображение на морско дъно с 2 делфина и с надпис Bulgaria.",
                            ImageUrl = "https://i.ibb.co/6Xj3SVh/Towel-Dolphin.jpg",
                            ManufacturerId = 4,
                            Name = "Плажна хавлия DREAMFOX 75 x 150 cm.",
                            Price = 4.80m,
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("313e431e-65fc-4c1e-9d9d-363b764d4e7f"),
                            Barcode = 57523,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Памучна плажна хавлия с котвички, синя. Грамаж: 360 гр.",
                            ImageUrl = "https://i.ibb.co/y08sGtL/Towel-Plain-Blue.jpg",
                            ManufacturerId = 4,
                            Name = "Плажна хавлия DREAMFOX 70 x 140 cm.",
                            Price = 9.30m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("ed0a1b2c-c31a-42aa-932b-3fdc56c7030d"),
                            Barcode = 57526,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Памучна плажна хавлия с ананаси, розова. Грамаж: 360 гр.",
                            ImageUrl = "https://i.ibb.co/BCMvsmq/Towen-Plain-Pink.jpg",
                            ManufacturerId = 4,
                            Name = "Плажна хавлия DREAMFOX 70 x 140 cm.",
                            Price = 9.30m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("7c091438-9bf9-4c4f-9b03-8a03b041b1a0"),
                            Barcode = 56130,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Микрофибърна плажна хавлия с изоображение на русалка и надписи.",
                            ImageUrl = "https://i.ibb.co/Fn52s1n/Towel-Mermaid.jpg",
                            ManufacturerId = 4,
                            Name = "Плажна хавлия DREAMFOX 75 x 150 cm.",
                            Price = 5.00m,
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("429ac0e3-d016-4daa-a146-6b33ac1107a0"),
                            Barcode = 58922,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Микрофибърна плажна хавлия с изоображение на китара поставена на плаж.",
                            ImageUrl = "https://i.ibb.co/XpYVKZ4/Towen-Seaside.jpg",
                            ManufacturerId = 4,
                            Name = "Плажна хавлия DREAMFOX 75 x 150 cm.",
                            Price = 4.80m,
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("b6c24e23-f742-4532-9521-e47e869ed830"),
                            Barcode = 55555,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Чадърите на \"Публиидея\" са перфектният аксесоар за горещите дни на плажа и ще Ви предпази парещите слънчеви лъчи. Лeceн е зa мoнтиpaнe, ocигypявa зaщитa oт cлънчeвитe лъчи UV25. Moжe лecнo дa бъдe нагласен в кoятo и дa e пocoкa, блaгoдapeниe нa чупещошд рамо. Диаметър: 100 см.",
                            ImageUrl = "https://i.ibb.co/6vxZ7wZ/Umbrella-Plain.jpg",
                            ManufacturerId = 10,
                            Name = "Пкажен чадър ПУБЛИИДЕЯ, тъмно-зелен.",
                            Price = 14.85m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("3e66d821-1bbb-446f-adb4-c480b09512cf"),
                            Barcode = 44443,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Чадърите на \"Публиидея\" са перфектният аксесоар за горещите дни на плажа и ще Ви предпази парещите слънчеви лъчи. Лeceн е зa мoнтиpaнe, ocигypявa зaщитa oт cлънчeвитe лъчи UV20+. Moжe лecнo дa бъдe нагласен в кoятo и дa e пocoкa, блaгoдapeниe нa чупещошд рамо. Диаметър: 100 см.",
                            ImageUrl = "https://i.ibb.co/vvtYT55/Umberlla-Plams.jpg",
                            ManufacturerId = 10,
                            Name = "Плажен чадър ПУБЛИИДЕЯ, палми",
                            Price = 6.80m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("fcc42273-0a13-4c94-9de8-6511cd55ec54"),
                            Barcode = 44442,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Чадърите на \"Публиидея\" са перфектният аксесоар за горещите дни на плажа и ще Ви предпази парещите слънчеви лъчи. Лeceн е зa мoнтиpaнe, ocигypявa зaщитa oт cлънчeвитe лъчи UV20+. Moжe лecнo дa бъдe нагласен в кoятo и дa e пocoкa, блaгoдapeниe нa чупещошд рамо. Диаметър: 100 см.",
                            ImageUrl = "https://i.ibb.co/Sv0DmBy/Umbrella-Plants.jpg",
                            ManufacturerId = 10,
                            Name = "Плажен чадър ПУБЛИИДЕЯ, растения",
                            Price = 7.50m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("e0de7594-2437-44d7-9c8e-74cf3e319dcc"),
                            Barcode = 44444,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Чадърите на \"Публиидея\" са перфектният аксесоар за горещите дни на плажа и ще Ви предпази парещите слънчеви лъчи. Лeceн е зa мoнтиpaнe, ocигypявa зaщитa oт cлънчeвитe лъчи UV20+. Moжe лecнo дa бъдe нагласен в кoятo и дa e пocoкa, блaгoдapeниe нa чупещошд рамо. Диаметър: 100 см.",
                            ImageUrl = "https://i.ibb.co/ZmM9rZP/Umbrella-Starfish.jpg",
                            ManufacturerId = 10,
                            Name = "Плажен чадър ПУБЛИИДЕЯ, морски звезди",
                            Price = 6.80m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("ec2a7b54-28ed-42e1-be4f-a1560e7dd450"),
                            Barcode = 56718,
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Плажна чанта с плетени дръжки и изообразени дини и черни палмови листа на бял фон.",
                            ImageUrl = "https://i.ibb.co/2MFJmGv/Bag-Watermellon.jpg",
                            ManufacturerId = 2,
                            Name = "Плажна Coveri Collection 53х37х19",
                            Price = 8.50m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("b2d7ca4d-7fe3-4fee-b789-7e680c8ba4f6"),
                            Barcode = 56724,
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Плажна чанта с плетени дръжки и изообразени котва на син фон с рози. ",
                            ImageUrl = "https://i.ibb.co/BZYy30X/Bag-Anchor.jpg",
                            ManufacturerId = 2,
                            Name = "Плажна чанта Coveri Collection 53х37х19",
                            Price = 8.50m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("0ba1f449-3e50-4022-b0a4-a83a110ef4d2"),
                            Barcode = 56723,
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Плажна чанта с плетени дръжки и изообразени макове на черно-бял фон.",
                            ImageUrl = "https://i.ibb.co/LPnV4tL/BagPoppy.jpg",
                            ManufacturerId = 2,
                            Name = "Плажна чанта Coveri Collection 53х37х19",
                            Price = 8.50m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("33070e7c-055f-4a8b-86f8-7a64bcfada22"),
                            Barcode = 56721,
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Плажна чанта с плетени дръжки и изообразени миди и рулове на бял фон.",
                            ImageUrl = "https://i.ibb.co/RhKgqG2/BagClams.jpg",
                            ManufacturerId = 2,
                            Name = "Плажна чанта Coveri Collection 53х37х19",
                            Price = 8.50m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("881f3736-b18b-4462-855c-ef04a4179bd2"),
                            Barcode = 56720,
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Плажна чанта с плетени дръжки и изообразени орхидеи на бял фон.",
                            ImageUrl = "https://i.ibb.co/8bQ32MJ/Bag-Orchid.jpg",
                            ManufacturerId = 2,
                            Name = "Плажна чанта Coveri Collection 53х37х19",
                            Price = 8.50m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("4e87766e-246f-470b-bec7-e537fc0085fe"),
                            Barcode = 18040,
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Комплектът съдържа гребло, лопатка, сито и формичка риба. Кофичката е с диаметър 29см.",
                            ImageUrl = "https://i.ibb.co/5vfvRwN/Toy-Bucket-Disney.jpg",
                            ManufacturerId = 1,
                            Name = "Vinex - Комплект кофичка за пясък Дисни",
                            Price = 8.25m,
                            Stock = 16
                        },
                        new
                        {
                            Id = new Guid("b7aff813-19de-4a67-bb59-4d1ea6db7118"),
                            Barcode = 17005,
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Комплектът съдържа гребло, лопатка, сито и формички риба и костенурка. Кофичката е с диаметър 26см.",
                            ImageUrl = "https://i.ibb.co/cw3903C/Toy-Bucket-Plain.jpg",
                            ManufacturerId = 1,
                            Name = "Vinex - Комплект кофичка за пясък Дисни",
                            Price = 6.00m,
                            Stock = 16
                        },
                        new
                        {
                            Id = new Guid("377b49a5-5dad-4c8c-a11c-496cc3868810"),
                            Barcode = 10805,
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Комплектът съдържа гребло, лопатка, сито и формички риба, костенурка, мида и морска звезда. Кофичката е с диаметър 26см.",
                            ImageUrl = "https://i.ibb.co/cX57F5w/Toy-Bucket-Cartoon.jpg",
                            ManufacturerId = 1,
                            Name = "Vinex - Комплект кофичка за пясък Дисни",
                            Price = 10.50m,
                            Stock = 16
                        },
                        new
                        {
                            Id = new Guid("8f21f133-0bee-499a-99cc-00ca1da2f602"),
                            Barcode = 33306,
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Комплектът съдържа гребло, лопатка, сито, лейка и три формички замък. Кофичката е квадратна, с размери 16 х 16 см.",
                            ImageUrl = "https://i.ibb.co/86dL7D5/Toy-Bucket-Square.jpg",
                            ManufacturerId = 1,
                            Name = "Vinex - Комплект кофичка за пясък Дисни",
                            Price = 6.40m,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("458353ba-4042-43fb-bdd4-74ce6d320df4"),
                            Barcode = 36113,
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Лопата за пясък, дървена дръжка с дължина 62 см.",
                            ImageUrl = "https://i.ibb.co/WHxnBfw/Toy-Shovel.jpg",
                            ManufacturerId = 1,
                            Name = "Vinex - Лопата за пясък",
                            Price = 3.20m,
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("703f98c9-c87d-4254-8971-852c1cd950dd"),
                            Barcode = 58849,
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Воден пистолет CPS TOYS, асортимент 38 см. Механизъм на помпата - функция помпане, дължина: 38 см, обем на резервоара: 900 мл, изстрелва водата до 8 метра!",
                            ImageUrl = "https://i.ibb.co/jf72Vv7/Toy-Water-Gun.jpg",
                            ManufacturerId = 3,
                            Name = "Воден пистолет CPS TOYS 50см",
                            Price = 7.40m,
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("8187e83a-bf2f-4076-b5bd-151aa009ada3"),
                            Barcode = 42178,
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Плувна маска за цяло лице в мрежа S, M силикон, синьо, електрикаво зелено, черно",
                            ImageUrl = "https://i.ibb.co/Ycbbt1d/Swimming-Mask.jpg",
                            ManufacturerId = 6,
                            Name = "Маска за плуване за цяло лице Shenzhen Befine Sports Goods ReefRider",
                            Price = 33.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("775ba055-eec9-416e-8dfd-ea1cc680bb3d"),
                            Barcode = 59139,
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Плавниците cа подходящи за гмуркане или тренировки по плуване. Tяхната площ ще даде възможноcт на вcеки любител на водните приключения да cе движи много по-бързо!",
                            ImageUrl = "https://i.ibb.co/xFGh6x2/Swimming-Fins-Children.jpg",
                            ManufacturerId = 9,
                            Name = "Плавници Vanguard Watersports Super Sport, 35-37 номер",
                            Price = 19.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("d63b2f1f-32e4-478b-a757-2d579755e948"),
                            Barcode = 42181,
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Плавниците cа подходящи за гмуркане или тренировки по плуване. Tяхната площ ще даде възможноcт на вcеки любител на водните приключения да cе движи много по-бързо!",
                            ImageUrl = "https://i.ibb.co/vZN4MxL/Swimming-Fins-Adult.jpg",
                            ManufacturerId = 9,
                            Name = "Плавници Vanguard Watersports Mega Sport, 39-43 номер",
                            Price = 19.50m,
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("3f987ddd-517e-4093-868a-24fd8504c45d"),
                            Barcode = 24040,
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Шапка за плуване, текстил. Размери: 21 х 12 см.",
                            ImageUrl = "https://i.ibb.co/hZnkbPF/Swimming-Cap.jpg",
                            ManufacturerId = 9,
                            Name = "Шапка за плуване Vanguard Watersports, текстил",
                            Price = 1.35m,
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("a05a0b7e-cbf4-4616-92e3-328c3f0ae779"),
                            Barcode = 31386,
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Плувни очила, силикон, цветни, здраво прелепващи 13 см. ",
                            ImageUrl = "https://i.ibb.co/BsKqYC7/Swimming-Goggles-Children.jpg",
                            ManufacturerId = 6,
                            Name = "Очила за плуване за деца Shenzhen Befine Sports Goods Fun Goggles",
                            Price = 4.50m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("5e64307e-5501-43ff-9730-51a9c7a42468"),
                            Barcode = 51375,
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Плувни очила за възрастни, широки, черен силикон 18х8 см.",
                            ImageUrl = "https://i.ibb.co/y0PGtTq/Swimming-Goggles-Adult.jpg",
                            ManufacturerId = 6,
                            Name = "Очила за плуване за възрастни Shenzhen Befine Sports Goods Water Sport",
                            Price = 7.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("b15ebf26-a758-4da1-866f-f11ca8c4b845"),
                            Barcode = 42174,
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Мундщук от поливинилхлорид за меко и удобно прилягане. Дихателна тръба със среден диаметър и дължина 42 см. Дизайн идеален за деца.",
                            ImageUrl = "https://i.ibb.co/FYgw02D/Swimming-Snorkel-Children.jpg",
                            ManufacturerId = 6,
                            Name = "Детски шнорхел Shenzhen Befine Sports Goods Hi-Flo",
                            Price = 3.65m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("387795ce-3a33-4864-b3e9-7c5f93779d36"),
                            Barcode = 42172,
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Шнорхел за възрастни с удобен термопластичен гумен мундщукшнорхел. Дихателна тръба с висококачествена P.V.C. изработка и дължина 42 см.",
                            ImageUrl = "https://i.ibb.co/9v2Qr7q/Swimming-Snorkel-Adults.jpg",
                            ManufacturerId = 6,
                            Name = "Шнорхел Shenzhen Befine Sports Goods Easy-Flow",
                            Price = 5.50m,
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("8f53bbac-ae6b-4064-bc63-4fc58cf3c11d"),
                            Barcode = 58546,
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Алигаторите нe ca тoлкoвa cтpaшни кoлкoтo cи миcлитe. Сeгa имaтe възмoжнocт дa ce зaбaвлявaтe c eдин oт тях в бaceйнa, морeто или дори и нa cушaтa. Алигаторът e c paзмepи, кoитo ca cхoдни c тeзи нa иcтинcкитe му cъбpaтя и e гoтoв зa мнoгo игpи c вaшият мaлчугaн. Изработен е от качествен винил и има 1 здрaва дръжка за захващане зa по-голямa уcтойчивоcт и cигурноcт нa дeтeто. Размер: 168 х 86 см.",
                            ImageUrl = "https://i.ibb.co/PsLkswc/Floaty-Crocodile.jpg",
                            ManufacturerId = 5,
                            Name = "Надуваема играчка Алигатор INTEX LIL' Gator Ride-on, малък",
                            Price = 19.85m,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("00595e61-e366-4ba0-8912-5755aab38300"),
                            Barcode = 49230,
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кaквo мoжe дa нaпpaви плувaнeтo в бaceйнa или в мopeтo oщe пo-зaбaвнo? Нaпpимep aкo дeтeтo влeзe във вoдaтa с пояс с брокат със забавен дизайн във формата на еднорог. Размер: 90 см.",
                            ImageUrl = "https://i.ibb.co/j5MMjgM/Floaty-Unicorn.jpg",
                            ManufacturerId = 5,
                            Name = "Детски надуваем пояс INTEX Пони-Еднорог",
                            Price = 11.80m,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("fee21581-2eca-47a1-afe6-6f50842aa026"),
                            Barcode = 36727,
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Надуваем остров с диаметър 70 см. Свеж дизайн. Въже за захващане.",
                            ImageUrl = "https://i.ibb.co/7tz51mq/Floaty-Melon.jpg",
                            ManufacturerId = 7,
                            Name = "Надуваем поясн Диня Shui Zhong Bao Watermelon",
                            Price = 4.20m,
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("0f30c4aa-1624-415f-9c88-dea00f5964ab"),
                            Barcode = 56113,
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изработен е от качествен винил и има 4 въздушни камери, голям външeн пpъcтeн зa по-голямa cтaбилноcт и отвоpи зa кpaчeтaтa нa дeтeто, които оcигуpявaт нeговaтa бeзопacноcт и пpeдотвpaтявaт вepоятноcттa от изхлузване от пояca.",
                            ImageUrl = "https://i.ibb.co/H2wNG86/Floaty-Turtle-Babies.jpg",
                            ManufacturerId = 7,
                            Name = "Бебешки надуваем пояс - проходилка Shui Zhong Bao Turtle",
                            Price = 5.75m,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("81bd866b-81ed-4f27-a9d0-bbd7c35badc7"),
                            Barcode = 58762,
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Насладете се на почивката със забавния надуваем дюшек във формата на близалка от Intex. Той е достатъчно голям, за да се чувствате удобно и комфортно върху него. Можете да го ползвате и в басейна и на плажа. Изработен е от висококачествен винил, което го прави устойчив на надраскване и разкъсване.",
                            ImageUrl = "https://i.ibb.co/1dzzG9V/Floaty-Ice-Cream.jpg",
                            ManufacturerId = 5,
                            Name = "Надуваем дюшек сладолед - фунийка INTEX, 224 Х 107см",
                            Price = 14.50m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("08b77dd4-fec1-4e24-8108-64583423f04e"),
                            Barcode = 59720,
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Отпуснете се в басейна и се забавлявайте на следващото парти това лято с този надуваем дюшек. Забавният дизайн създава освежаващо и забавно настроение, докато релаксирате на слънце през цялото лято.",
                            ImageUrl = "https://i.ibb.co/G0WBydZ/Floaty-Bed.jpg",
                            ManufacturerId = 5,
                            Name = "Надуваем дюшек INTEX, 183 х 69 х 25см",
                            Price = 10.60m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("a19aa385-e48c-4c74-966c-7fa1c6e2a7a3"),
                            Barcode = 58786,
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Надуваем дюшек Ангелски крила INTEX. Размери и тегло - Размери: 251 x 106 см.; Тегло: 3.47 кг.",
                            ImageUrl = "https://i.ibb.co/K7LDFSq/Floaty-Wings.jpg",
                            ManufacturerId = 5,
                            Name = "Надуваем дюшек Ангелски крила INTEX",
                            Price = 47.70m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("ddef6760-a0f6-4323-badc-259a5727ea6a"),
                            Barcode = 101730,
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Висококачествена топка с диаметър 21см. Игрите с топка ще помогнат на децата да задоволят естественото си желание за движение по забавен начин. Те използват енергията си по подходящ начин - активното движение на чист въздух е полезно за здравето и в същото време носи радост от играта.",
                            ImageUrl = "https://i.ibb.co/3h3MV9H/Ball-Miami.jpg",
                            ManufacturerId = 8,
                            Name = "Star  - Волейболна топка Miami Beach, 21см",
                            Price = 6.30m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("419de771-8456-44a7-854d-c32c7d29c66a"),
                            Barcode = 101019,
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Висококачествена топка с диаметър 21см. Игрите с топка ще помогнат на децата да задоволят естественото си желание за движение по забавен начин. Те използват енергията си по подходящ начин - активното движение на чист въздух е полезно за здравето и в същото време носи радост от играта.",
                            ImageUrl = "https://i.ibb.co/pQJZTcp/Ball-Bora-Bora.jpg",
                            ManufacturerId = 8,
                            Name = "Star  - Волейболна топка Bora Bora, 21см",
                            Price = 6.30m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("d8fe7d3f-e197-4d5f-8f41-d95487419c2d"),
                            Barcode = 101090,
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Висококачествена топка с диаметър 21см. Игрите с топка ще помогнат на децата да задоволят естественото си желание за движение по забавен начин. Те използват енергията си по подходящ начин - активното движение на чист въздух е полезно за здравето и в същото време носи радост от играта.",
                            ImageUrl = "https://i.ibb.co/HgMXxMb/Ball-Beach-Palms.jpg",
                            ManufacturerId = 8,
                            Name = "Star  - Волейболна топка Beach Volley, 21см",
                            Price = 6.30m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("397b42b7-2ccb-43e9-882c-bc5a58f4ca56"),
                            Barcode = 101011,
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Висококачествена топка с диаметър 21см. Игрите с топка ще помогнат на децата да задоволят естественото си желание за движение по забавен начин. Те използват енергията си по подходящ начин - активното движение на чист въздух е полезно за здравето и в същото време носи радост от играта.",
                            ImageUrl = "https://i.ibb.co/qnd7sVN/Ball-Water-Polo.jpg",
                            ManufacturerId = 8,
                            Name = "Star  - Волейболна топка Water Polo, 21см",
                            Price = 6.15m,
                            Stock = 10
                        });
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.ProductOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SingularPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Address", b =>
                {
                    b.HasOne("BeachEquipmentStore.Data.Models.ApplicationUser", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.CartItem", b =>
                {
                    b.HasOne("BeachEquipmentStore.Data.Models.ApplicationUser", "Customer")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeachEquipmentStore.Data.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Order", b =>
                {
                    b.HasOne("BeachEquipmentStore.Data.Models.ApplicationUser", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Product", b =>
                {
                    b.HasOne("BeachEquipmentStore.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeachEquipmentStore.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.ProductOrder", b =>
                {
                    b.HasOne("BeachEquipmentStore.Data.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeachEquipmentStore.Data.Models.Product", "Product")
                        .WithMany("ProductsOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BeachEquipmentStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BeachEquipmentStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeachEquipmentStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BeachEquipmentStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("BeachEquipmentStore.Data.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("ProductsOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
